# Generated by Django 3.1.4 on 2021-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('start_of_academic_year', models.DateField()),
                ('end_of_academic_year', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
